### PR TITLE
Test PotgreSQL 9.3 instead of 9.5

### PR DESCRIPTION
**Pull request by strk**

### CODE REVIEW

**Comment by strk** [comment]
I've published 9.3 packages of dbpatch and tableversion, restarting CI next

**Comment by strk** [comment]
Bill: tests worked now, it is probably good to ensure we still support 9.3...

**Review by billgeo — APPROVED** [review]
Great. LGTM. Do we need to do this for other repos too? If so please create a ticket for that.

**Comment by strk** [comment]
I guess it'd be useful to do for other repos too, yes.

**Pull request merged**
