### PR TITLE
Do not use table_version functions if not available

### LINKED ISSUE #4: Error installing without table versioning
The patch BDE - 1.0.2: Remove annotations column from bde.crs_work assumes that table_version.ver_is_table_versioned function is defined, which fails if table versioning is not installed.

### PR DESCRIPTION
**Pull request by strk**
Fixes #4

### CODE REVIEW

**Comment by palmerj** [comment]
In regards to syntax errors really need to get CI going on this package

**Comment by strk** [comment]
Indeed, I filed #12 for enabling CI. Should I wait for @ccrook revision on this before merge ?

**Comment by palmerj** [comment]
Nope you can merge now.

**Comment by imincik** [comment]
> In regards to syntax errors really need to get CI going on this package

@palmerj , Yes, I plan tests and CI for all BDE Processor components in @strk next iteration

**Comment by palmerj** [comment]
Great. Good plan.

**Pull request merged**
