### PR TITLE
feat: only alter table owner if really needed

### PR DESCRIPTION
**Pull request by strk**
Reduces the odds of deadlocks.

See also https://github.com/linz/linz-lds-bde-schema/pull/218

### CODE REVIEW

**Comment by imincik** [comment]
Test failing here.

**Comment by strk** [comment]
> Test failing here.

Tests are failing because CI in this branch is also testing PostgreSQL < 9.5 which does not support the syntax used in this PR. Ok to raise the dependency or shall I aim at rewriting it to retain compatibility ? Same issue exists for https://github.com/linz/linz-lds-bde-schema/pull/218#issuecomment-618335780

**Comment by strk** [comment]
Trying a PG9.3 compatible version of the patch..

**Comment by strk** [comment]
The patch is verified to be PG9.3 compatible by CI, great :) - approval needed to merge

**Pull request merged**
