### PR TITLE
Patch: View to support AIMS (QGIS Plugin) parcel labeling

### PR DESCRIPTION
**Pull request by SPlanzer**

### CODE REVIEW

**Comment by SPlanzer** [comment]
@jrlinz could you review this view I have added to the bde schema via a patch

**Comment by jrlinz** [comment]
The formatting of the patch looks okay. Can't really comment on the functionality but assume adding a new view will have litle impact

**Comment by strk** [comment]
Just a suggestion:  you could use `$dollar$` quoting to have a more comfortable quote usage in the patch body, see https://github.com/linz/linz-bde-schema/pull/13/files

**Comment by strk** [comment]
@jrlinz see #16 for impact analysis - your comment is welcome on the suggested version semantic

**Comment by strk** [comment]
@jrlinz there's now a functional testsuite, could you please add a test for the new view ?
See https://github.com/linz/linz-bde-schema/tree/master/test

**Comment by strk** [comment]
And as per https://github.com/linz/linz-bde-schema/issues/16#issuecomment-303834287 please update the patch title to target 1.1.0, not 1.0.3

**Comment by strk** [comment]
@SPlanzer do you still want this patch included in 1.1.0 ?

**Comment by SPlanzer** [comment]
@strk this was to support a QGIS plugin release that has stalled. I will close and forget about this for now.

Cheers

**Pull request closed without merging**
