### PR TITLE
Update schema comments from LDS Full Data dictionary 2.6

### PR DESCRIPTION
**Pull request by strk**
Some schema comments, which can only be extracted from XML,
are left untouched.

Comments for deprecated tables/layers are retained

References #200 (although no column comments are included)

### CODE REVIEW

**Comment by strk** [comment]
Interesting enough: ERROR:  relation "bde.crs_ordinate_adjustment" does not exist
The PDF document contains documentation for this table, but we do not have it in schema definition !

\cc @billgeo

**Comment by strk** [comment]
According to https://data.linz.govt.nz/table/89377-landonline-ordinate-adjustment/ the table was added in October 2017 - did we miss picking it up ?

**Comment by strk** [comment]
I've updated the patch to NOT include the documented but missing table

**Comment by strk** [comment]
NOTE: changes so far still do not have the crs_ttl_inst_protect table documented

**Comment by billgeo** [comment]
@iharrison can you comment on Sandro's questions above about missing BDE tables etc. I presume these shouldn't be in the Data Dictionary?

**Comment by iharrison** [comment]
If the ordinate adjustment table is missing it should be included. It's still a current table on the LDS.

We don't want to include crs_ttl_inst_protect in any public documentation.

**Pull request merged**
