### PR TITLE
Add linz-bde-schema-load script to simplify installing schema

### PR DESCRIPTION
**Pull request by strk**
The script can also be used to upgrade an existing database.

### CODE REVIEW

**Comment by imincik** [comment]
Hi @strk , I am not greatest Makefile expert, but is hardcoding of `bindir=${DESTDIR}/usr/local/bin` right approach. Debian package can't install executables to `/usr/local` .

**Comment by imincik** [comment]
Without having too much chance to think about that in depth, it looks as very good idea

**Comment by strk** [comment]
You're right @imincik that `/usr/local` was not a good choice, it was already fixed with 51b0e3e6ae925750e7a3cb9cec9242e22944f13c

**Comment by imincik** [comment]
@strk , thanks for fix.

**Pull request merged**
