### PR TITLE
feat: Use unlimited length for bde.crs_proprietor.corporate_name column

### PR DESCRIPTION
**Pull request by l0b0**
Review where this column is used and update those column definitions as well (including other repos!).

### CODE REVIEW

**Review by billgeo — COMMENTED** [review]
Looks good, but should we add all the other downstream tables and columns that need to change into this PR?

**Comment by l0b0** [comment]
> Looks good, but should we add all the other downstream tables and columns that need to change into this PR?

That's why it's in draft :)

**Comment by billgeo** [comment]
As per the discussion here. I think we can close this PR in favour of making changes to linz-lds-bde-schema.

**Comment by l0b0** [comment]
Reopening for the release process.

**Comment by l0b0** [comment]
Fixed in wrong repo.

**Pull request closed without merging**
