### PR TITLE
Test against multiple PostgreSQL versions

### PR DESCRIPTION
**Pull request by strk**

### CODE REVIEW

**Comment by imincik** [comment]
@strk , thanks for this.

Ticket https://github.com/linz/postgresql-dbpatch/issues/4  is closed, so workaround from this patch can be removed.
```
sudo env "PATH=$PATH" make install || true
```

**Comment by strk** [comment]
Workaround can only be removed if we install dbpatch from master branch. Right now Travis is installing latest release, which is 1.0.1 (affected by the bug). I'd drop the workaround once we have 1.0.2 available ( https://github.com/linz/postgresql-dbpatch/issues/7 )

**Comment by imincik** [comment]
Thanks @strk , I realized that as well few hours after I wrote my comment. Please keep it in mind. Thanks.

**Comment by strk** [comment]
I've added dbpatch 1.0.2 tagging to this week plan, will include removing the workaround from multiple repositories

**Comment by imincik** [comment]
Please add Debian packaging tasks for me and I will do them during this week.

**Pull request merged**
